apiVersion: v1
kind: Secret
metadata:
  name: tl-secrets
  namespace: togetherlearn
type: Opaque
stringData:
  jwt-secret: "tl-jwt-secret-change-in-production-min-32-chars"
  db-password: "tl_postgres_pass"
  redis-url: "redis://:redis_pass@redis:6379"
  rabbitmq-uri: "amqp://tl:tl_password@rabbitmq:5672"
  minio-access-key: "minio"
  minio-secret-key: "minio_pass"
  grafana-password: "admin"
