server:
  port: 8088

spring:
  application:
    name: file-service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

aws:
  s3:
    endpoint: ${AWS_S3_ENDPOINT:http://localhost:9000}
    public-url: ${AWS_S3_PUBLIC_URL:http://localhost:9000}
    access-key: ${AWS_ACCESS_KEY:minio}
    secret-key: ${AWS_SECRET_KEY:minio_pass}
    bucket: ${AWS_S3_BUCKET:tl-files}
    region: ${AWS_REGION:us-east-1}

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://zipkin:9411}/api/v2/spans
